# 依赖审查 Action
#
# 此Action会扫描Pull Request中变更的依赖清单文件，
# 展示PR中声明或更新的已知有漏洞的软件包版本。
# 一旦安装，如果工作流运行被标记为必需，则引入已知有漏洞软件包的PR将被阻止合并。
#
# 源代码仓库: https://github.com/actions/dependency-review-action
# 公开文档: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: '依赖审查'
on:
  pull_request:
    branches: [ "master" ]

# 如果在此工作流中使用依赖提交action，则需要设置以下权限:
#
# permissions:
#   contents: write
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read
  # 需要pull-requests的写权限来使用`comment-summary-in-pr`选项
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: '检出仓库'
        uses: actions/checkout@v4
      - name: '依赖审查'
        uses: actions/dependency-review-action@v4
        # 常用启用选项，参见 https://github.com/actions/dependency-review-action#configuration-options 获取所有可用选项
        with:
          comment-summary-in-pr: always
          fail-on-severity: moderate
          # deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          retry-on-snapshot-warnings: true