# 依赖审查操作
#
# 此操作将扫描作为拉取请求一部分而更改的依赖清单文件，
# 显示 PR 中声明或更新的包的已知易受攻击的版本。
# 安装后，如果工作流运行被标记为必需，
# 则引入已知易受攻击包的 PR 将被阻止合并。
#
# 源代码仓库: https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]

permissions:
 contents: read

jobs:
 dependency-review:
  runs-on: ubuntu-latest
  steps:
   - name: Harden the runner (Audit all outbound calls)
     uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
     with:
      egress-policy: audit

   - name: Audit - Workflow started
     run: |
       echo "Dependency Review workflow started for PR #${{ github.event.pull_request.number }}" >> audit.log
       echo "Triggered by: ${{ github.event.pull_request.user.login }}" >> audit.log
       echo "Commit SHA: ${{ github.sha }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 'Checkout Repository'
     uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
   - name: Audit - Code checked out
     run: |
       echo "Code checked out for dependency review" >> audit.log
       echo "Repository: ${{ github.repository }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 'Dependency Review'
     uses: actions/dependency-review-action@45529485b5eb76184ced07362d2331fd9d26f03f # v4
   - name: Audit - Dependency review completed
     run: |
       echo "Dependency review completed" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: Upload audit log
     uses: actions/upload-artifact@v4
     with:
       name: dependency-review-audit-log
       path: audit.log
       retention-days: 30
