name: Publish to npm

on:
 pull_request:
  branches:
   - main
  types: [closed]

permissions:
 id-token: write
 contents: read

jobs:
 publish:
  runs-on: ubuntu-latest
  if: github.event.pull_request.merged == true
  steps:
   - name: Harden the runner (Audit all outbound calls)
     uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
     with:
      egress-policy: audit

   - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

   - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
     with:
      node-version: '20'
      registry-url: 'https://registry.npmjs.org'

   # Ensure npm 11.5.1 or later is installed
   - name: Update npm
     run: npm install -g npm@latest

   - name: Install Yarn
     run: npm install -g yarn

   - name: Install dependencies
     run: yarn install --frozen-lockfile

   - name: Build project if script exists
     run: yarn run build || true

   - name: Publish package
     run: yarn publish
