# 此工作流使用了未经 GitHub 认证的 Actions。它们由第三方提供，并受其服务条款、隐私政策和支持文档的约束。

name: Scorecard 供应链安全检查
on:
 # 用于分支保护检查。仅支持默认分支。
 # 详情请参阅：https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
 # 确保维护检查定期更新。
 # 详情请参阅：https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
 branch_protection_rule:
 push:
  branches: ['main']

# 声明默认权限为只读。
permissions: read-all

jobs:
 analysis:
  name: Scorecard analysis
  runs-on: ubuntu-latest
  # `publish_results: true` 仅在从默认分支运行时生效。如果禁用，可以移除条件判断。
  if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
  permissions:
   # 需要将结果上传到代码扫描仪表板。
   security-events: write
   # 需要发布结果并获取徽章（参见下方的 publish_results）。
   id-token: write
   # 如果在私有仓库中安装，请取消注释以下权限。
   # contents: read
   # actions: read

  steps:
   - name: Harden the runner (Audit all outbound calls)
     uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
     with:
      egress-policy: audit

   - name: Audit - Workflow started
     run: |
       echo "Scorecard analysis workflow started" >> audit.log
       echo "Event type: ${{ github.event_name }}" >> audit.log
       echo "Branch: ${{ github.ref_name }}" >> audit.log
       echo "Default branch: ${{ github.event.repository.default_branch }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 'Checkout code'
     uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
     with:
      persist-credentials: false
   - name: Audit - Code checked out
     run: |
       echo "Code checked out for scorecard analysis" >> audit.log
       echo "Repository: ${{ github.repository }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 'Run analysis'
     uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
     with:
      results_file: results.sarif
      results_format: sarif
      # （可选）"write" PAT 令牌。如果您满足以下条件，请取消注释 `repo_token` 行：
      # - 您希望在 *公共* 仓库上启用分支保护检查，或
      # - 您在 *私有* 仓库上安装 Scorecard
      # 创建 PAT 的步骤请参考：https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional 。
      # repo_token: ${{ secrets.SCORECARD_TOKEN }}

      # 公共仓库：
      #   - 将结果发布到 OpenSSF REST API，方便用户访问
      #   - 允许仓库包含 Scorecard 徽章。
      #   - 详情请参阅：https://github.com/ossf/scorecard-action#publishing-results 。
      # 私有仓库：
      #   - `publish_results` 将始终设置为 `false`，无论此处输入的值是什么。
      publish_results: true
   - name: Audit - Scorecard analysis completed
     run: |
       echo "Scorecard analysis completed" >> audit.log
       echo "Results file: results.sarif" >> audit.log
       echo "Publish results: true" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   # 将运行结果作为工件上传（可选）。注释掉将禁用以 SARIF 格式将运行结果上传到仓库的 Actions 选项卡。
   - name: 'Upload artifact'
     uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
     with:
      name: SARIF file
      path: results.sarif
      retention-days: 5
   - name: Audit - SARIF artifact uploaded
     run: |
       echo "SARIF artifact uploaded" >> audit.log
       echo "Artifact name: SARIF file" >> audit.log
       echo "Retention days: 5" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   # 将结果上传到 GitHub 的代码扫描仪表板（可选）。
   # 注释掉将禁用将结果上传到您的仓库的代码扫描仪表板
   - name: 'Upload to code-scanning'
     uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v4.31.2
     with:
      sarif_file: results.sarif
   - name: Audit - Results uploaded to code scanning
     run: |
       echo "Results uploaded to code scanning" >> audit.log
       echo "SARIF file: results.sarif" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: Upload audit log
     uses: actions/upload-artifact@v5
     with:
       name: scorecard-audit-log
       path: audit.log
       retention-days: 30
