name: 自动总结新issues

on:
 issues:
  types: [opened]

permissions:
 contents: read

jobs:
 summary:
  runs-on: ubuntu-latest
  permissions:
   issues: write
   contents: read

  steps:
   - name: Harden the runner (Audit all outbound calls)
     uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
     with:
      egress-policy: audit

   - name: Audit - Workflow started
     run: |
       echo "Issue Summary workflow started" >> audit.log
       echo "Event type: ${{ github.event_name }}" >> audit.log
       echo "Issue number: ${{ github.event.issue.number }}" >> audit.log
       echo "Issue author: ${{ github.event.issue.user.login }}" >> audit.log
       echo "Issue title: ${{ github.event.issue.title }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 检出代码仓库
     uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
   - name: Audit - Code checked out
     run: |
       echo "Code checked out for issue summary" >> audit.log
       echo "Repository: ${{ github.repository }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 运行AI推理
     id: inference
     uses: actions/ai-inference@a1c11829223a786afe3b5663db904a3aa1eac3a2 # v2.0.1
     with:
      prompt: |
       请用一段话总结以下GitHub issue:
       标题: ${{ github.event.issue.title }}
       内容: ${{ github.event.issue.body }}
   - name: Audit - AI inference completed
     run: |
       echo "AI inference completed for issue #${{ github.event.issue.number }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: 以AI总结内容评论
     run: |
      if ! gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.response }}'; then
        echo "Warning: Failed to add comment to issue #${{ github.event.issue.number }}" >> audit.log
        echo "AI response: ${{ steps.inference.outputs.response }}" >> audit.log
        echo "Timestamp: $(date -u)" >> audit.log
        # Continue with the workflow even if this step fails
      fi
     env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      RESPONSE: ${{ steps.inference.outputs.response }}
   - name: Audit - Comment added to issue
     run: |
       echo "Comment added to issue #${{ github.event.issue.number }}" >> audit.log
       echo "Timestamp: $(date -u)" >> audit.log

   - name: Upload audit log
     uses: actions/upload-artifact@v4
     with:
       name: summarize-issues-audit-log
       path: audit.log
       retention-days: 30
