name: 自动总结新issues

on:
 issues:
  types: [opened]

permissions:
 contents: read

jobs:
 summary:
  runs-on: ubuntu-latest
  permissions:
   issues: write
   contents: read

  steps:
   - name: Harden the runner (Audit all outbound calls)
     uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
     with:
      egress-policy: audit

   - name: 检出代码仓库
     uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

   - name: 运行AI推理
     id: inference
     uses: actions/ai-inference@a1c11829223a786afe3b5663db904a3aa1eac3a2 # v2.0.1
     with:
      prompt: |
       请用一段话总结以下GitHub issue:
       标题: ${{ github.event.issue.title }}
       内容: ${{ github.event.issue.body }}

   - name: 以AI总结内容评论
     run: |
      gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.response }}'
     env:
      GH_TOKEN: ${{ secrets.TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      RESPONSE: ${{ steps.inference.outputs.response }}
