name: Sync to Multiple Repositories

on:
  pull_request:
    types: [ closed ]

jobs:
  sync-to-gitcode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置SSH密钥（Gitcode）
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 接受 GitCode 主机密钥
        run: |
          echo -e "Host gitcode.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts
      - name: 配置Git用户信息（Gitcode）
        run: |
          git config --global user.name "xiaomizhou"
          git config --global user.email "qixiaoxin@stu.sqxy.edu.cn"
      - name: 添加Gitcode远程仓库
        run: |
          git remote add gitcode git@gitcode.com:xiaomizhou/MZAPI-TS.git
      - name: 同步代码到Gitcode
        run: |
          git push gitcode master